/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityCityIdRouteImport } from './routes/city.$cityId'

const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRoute = CityCityIdRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/city/$cityId': typeof CityCityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/city/$cityId': typeof CityCityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/city/$cityId': typeof CityCityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favourites' | '/city/$cityId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favourites' | '/city/$cityId'
  id: '__root__' | '/' | '/favourites' | '/city/$cityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  CityCityIdRoute: typeof CityCityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  CityCityIdRoute: CityCityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
